apiVersion: v1
kind: Secret
metadata:
  name: phoenix-secrets
  namespace: phoenix
  labels:
    app: phoenix
    app.kubernetes.io/part-of: phoenix
type: Opaque
stringData:
  PHOENIX_SECRET: "phoenix-hybrid-cloud-demo-secret-key-2026-secure"
  PHOENIX_ADMIN_SECRET: "phoenix-admin-secret-key-hybrid-cloud-demo-2026"
  POSTGRES_PASSWORD: "phoenix"
