apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-archive
  namespace: hybridbank
  labels:
    app: postgres-archive
    app.kubernetes.io/part-of: hybridbank
spec:
  storageClassName: px-csi-db
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-archive
  namespace: hybridbank
  labels:
    app: postgres-archive
    app.kubernetes.io/part-of: hybridbank
    tier: database
    data-sensitivity: pii
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-archive
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-archive
        app.kubernetes.io/part-of: hybridbank
        tier: database
        data-sensitivity: pii
    spec:
      serviceAccountName: postgres-sa
      securityContext:
        runAsUser: 70
        fsGroup: 70
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: hybridbank
            - name: POSTGRES_PASSWORD
              value: hybridbank
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: pgdata-archive
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "hybridbank"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "hybridbank"]
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 512Mi
      volumes:
        - name: pgdata-archive
          persistentVolumeClaim:
            claimName: pgdata-archive
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-archive
  namespace: hybridbank
  labels:
    app: postgres-archive
    app.kubernetes.io/part-of: hybridbank
spec:
  selector:
    app: postgres-archive
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
