all:
  children:
    hub:
      hosts:
        onprem:
          kubeconfig: /tmp/kubeconfig-hub.yaml
          onprem_kubeconfig: /tmp/kubeconfig-onprem.yaml
          cluster_name: prem
          cloud: on-prem
          px_template: storagecluster-onprem
          data_zone: restricted
    managed:
      hosts:
        aro:
          kubeconfig: /tmp/kubeconfig-aro.yaml
          cluster_name: aro
          cloud: azure
          px_template: storagecluster-aro
          data_zone: general
          px_endpoint: "52.188.27.140:30901"
          # Azure-specific vars for LB and NSG automation
          azure_resource_group: aro-east-cluster-rg
          azure_lb_name: aro-east-p5kdw
          azure_lb_frontend_ip: public-lb-ip-v4
          azure_nsg_name: aro-east-p5kdw-nsg
        osd:
          kubeconfig: /tmp/kubeconfig-osd.yaml
          cluster_name: osd
          cloud: gcp
          px_template: storagecluster-osd
          data_zone: general
          px_endpoint: "34.24.49.50:30901"
