apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-banner
  namespace: online-boutique
data:
  FRONTEND_MESSAGE: "☁️ Running on ARO / Azure / eastus"
  CLUSTER_NAME: "aro-east"
  CLOUD_PROVIDER: "Azure"
  REGION: "eastus"
  BANNER_COLOR: "#0078d4"
