apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: ensure-hybridbank-namespace
  namespace: hybridbank
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/standards: Hybrid Cloud Demo
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: ensure-hybridbank-ns
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: hybridbank
                  labels:
                    app.kubernetes.io/part-of: hybridbank
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: ensure-hybridbank-ns-binding
  namespace: hybridbank
placementRef:
  name: all-clusters-placement
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
  - name: ensure-hybridbank-namespace
    kind: Policy
    apiGroup: policy.open-cluster-management.io
