apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: px-data-readiness
  namespace: hybridbank
  annotations:
    policy.open-cluster-management.io/categories: SC System and Communications Protection
    policy.open-cluster-management.io/standards: Hybrid Cloud Demo
    policy.open-cluster-management.io/controls: SC-28 Protection of Information at Rest
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: px-data-readiness-check
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: PersistentVolumeClaim
                metadata:
                  name: pgdata-core
                  namespace: hybridbank
                status:
                  phase: Bound
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: px-data-readiness-placement
  namespace: hybridbank
spec:
  clusterSets:
    - hybrid-cloud-demo
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            environment: demo
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: px-data-readiness-binding
  namespace: hybridbank
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: px-data-readiness-placement
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: px-data-readiness
